name = "gleam_erlang"

version = "1.3.0"
licences = ["Apache-2.0"]
description = "Types and functions for programs running on Erlang!"

repository = { type = "github", user = "gleam-lang", repo = "erlang" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]
gleam = ">= 1.11.0"

[dependencies]
gleam_stdlib = ">= 0.53.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
