name = "gleam_erlang"

version = "0.28.0"
licences = ["Apache-2.0"]
description = "A Gleam library for working with Erlang"

repository = { type = "github", user = "gleam-lang", repo = "erlang" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.33.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
